services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    network_mode: "host"
    environment:
      - WHATSAPP_API_KEY=${WAHA_API_KEY}
      - WHATSAPP_HOOK_URL=${WAHA_HOOK_URL}
      - WHATSAPP_HOOK_EVENTS=*
    volumes:
      - waha_data:/app/.sessions
    restart: unless-stopped

volumes:
  waha_data:
